### ISSUE TITLE
The total is not effected

### ISSUE THREAD

**Issue by prosenjeet123** [Sammyskills/Opencart-Payment-Discount#1]
At the checkout page the total amount is not effected by the payment discount offer, however the discount is applied at the time of payment but the visible amount is not subtracted with the discount amount 

screenshot
https://prnt.sc/q718t9

**Comment by sammyskills** [comment]
I just tested and the display was correct. 

How are you getting the wrong display?

Could this be related to your theme?

Screenshot:
https://prnt.sc/q73ii4

**Comment by prosenjeet123** [comment]
Hi , i am using Journal 3 theme with quick checkout option which comes with journal 3 letme know if it has to do anything with the theme.

**Comment by sammyskills** [comment]
Have you been able to get this to work now?

**Comment by prosenjeet123** [comment]
Nope still figuring out and will update you.

**Comment by sammyskills** [comment]
Okay.

I'll see if I can get the theme for testing.

**Comment by prosenjeet123** [comment]
You can download it from here its not recommended though but for testing purpose : http://bit.ly/2SI9C5l

**Comment by sammyskills** [comment]
Hi,

I've been able to get the theme **(version 3.0.44)** installed on a local server (localhost) using XAMPP, and I've done some tests. 

Here are my findings:
Checkout page: The display was perfect, even with the one-page ajax checkout that came bundled with the theme. See screenshots below:

![journal-1](https://user-images.githubusercontent.com/8720569/71615409-80e63e00-2bb1-11ea-89e1-f3d9ac310754.png)
![journal-2](https://user-images.githubusercontent.com/8720569/71615411-85aaf200-2bb1-11ea-927f-a62a736de9bc.png)

> Whenever you enable / disable or delete a modification you need to click the refresh button to rebuild your modification cache!

Have you tried rebuilding your modification cache? Please access your Opencart Admin and go to Extensions > Modifications and click on the blue Refresh button (top right corner).
