### ISSUE TITLE
Sort order not working for invoice

### ISSUE THREAD

**Issue by prosenjeet123** [Sammyskills/Opencart-Payment-Discount#2]
Hi Again, the sort order is not working in the invoice

https://prnt.sc/qceqsj

**Comment by sammyskills** [comment]
The sort order should be a lower number than the total.

The order for the total is already displayed in the admin area of the extension.

Please check.

**Comment by prosenjeet123** [comment]
The sort order is working fine the frontend (checkout) but its not working in the admin nor invoice
Sort Order:
https://prnt.sc/qgq1z9

**Comment by sammyskills** [comment]
I really do not understand what you mean by "not working".

How exactly is it not working in the admin? With this screenshot: https://prnt.sc/qgq1z9, after saving, how does it appear in the frontend?

Also, how is it not working in the invoice? A screenshot, maybe?

**Comment by prosenjeet123** [comment]
The sorting order is not working it's working at the checkout page but the sort order setting is not effecting the admin>orders>invoice when you click on invoice the sorting is not applied.
![image](https://user-images.githubusercontent.com/12624294/71611628-6cf60880-2bc0-11ea-9718-98c9050ef4f5.png)

**Comment by prosenjeet123** [comment]
This is the screenshot of the invoice:
![image](https://user-images.githubusercontent.com/12624294/71611634-8303c900-2bc0-11ea-990a-5124e0b2d186.png)

**Comment by sammyskills** [comment]
Okay.

I'll check it out.

**Comment by sammyskills** [comment]
The sort order works fine from my end. I tested with version 3.0.44 of the Journal theme. I suggest you update your theme.

![journal-2](https://user-images.githubusercontent.com/8720569/71615598-4204b800-2bb2-11ea-8706-e29d22c0f4ba.png)

The invoice also works fine.
![journal-3](https://user-images.githubusercontent.com/8720569/71615613-547ef180-2bb2-11ea-8dda-a5fc7097e7ff.png)
![journal-4](https://user-images.githubusercontent.com/8720569/71615616-5779e200-2bb2-11ea-948b-20afbfe3199f.png)

Here's what I suggest:
1. Rebuild your modification cache. 
Access your Opencart Admin and go to Extensions > Modifications and click on the blue Refresh button (top right corner). 
If this doesn't solve the problem, please consider

2. Updating your theme to the latest version.
